package it.eng.hsm.test.itagile.firmaremota.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1 2017-08-29T17:56:04.083+02:00 Generated source version:
 * 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://ws.firmaremota.itagile.it", name = "RemoteSignatureXades")
@XmlSeeAlso({ ObjectFactory.class })
public interface RemoteSignatureXades {

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignatureXades/signRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignatureXades/signResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignatureXades/sign/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "sign", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.Sign")
    @ResponseWrapper(localName = "signResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignResponse")
    @WebResult(name = "signReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] sign(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "content", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] content,
            @WebParam(name = "digestType", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestType,
            @WebParam(name = "certificate", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] certificate,
            @WebParam(name = "params", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureXadesParams params)
            throws RemoteSignatureExceptionException;
}