/*
 * Engineering Ingegneria Informatica S.p.A.
 *
 * Copyright (C) 2023 Regione Emilia-Romagna
 * <p/>
 * This program is free software: you can redistribute it and/or modify it under the terms of
 * the GNU Affero General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 * <p/>
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 * <p/>
 * You should have received a copy of the GNU Affero General Public License along with this program.
 * If not, see <https://www.gnu.org/licenses/>.
 */

package it.eng.hsm.test.itagile.firmaremota.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1 2017-08-29T17:59:15.446+02:00 Generated source version:
 * 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://ws.firmaremota.itagile.it", name = "RemoteSignature")
@XmlSeeAlso({ ObjectFactory.class })
public interface RemoteSignature {

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/verifyCertificateRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/verifyCertificateResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/verifyCertificate/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "verifyCertificate", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.VerifyCertificate")
    @ResponseWrapper(localName = "verifyCertificateResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.VerifyCertificateResponse")
    @WebResult(name = "verifyCertificateReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public java.util.List<it.eng.hsm.test.itagile.firmaremota.ws.CertificateStatus> verifyCertificate(
            @WebParam(name = "X509Cert", targetNamespace = "http://ws.firmaremota.itagile.it") java.util.List<byte[]> x509Cert)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampTokenRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampTokenResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampToken/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "timestampToken", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.TimestampToken")
    @ResponseWrapper(localName = "timestampTokenResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.TimestampTokenResponse")
    @WebResult(name = "timestampTokenReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] timestampToken(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "digest", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] digest,
            @WebParam(name = "digestAlg", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestAlg)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampDetachedRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampDetachedResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampDetached/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "timestampDetached", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.TimestampDetached")
    @ResponseWrapper(localName = "timestampDetachedResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.TimestampDetachedResponse")
    @WebResult(name = "timestampDetachedReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] timestampDetached(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "digest", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] digest,
            @WebParam(name = "digestAlg", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestAlg)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/changeUserPasswordRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/changeUserPasswordResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/changeUserPassword/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "changeUserPassword", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.ChangeUserPassword")
    @ResponseWrapper(localName = "changeUserPasswordResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.ChangeUserPasswordResponse")
    public void changeUserPassword(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "userid", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String userid,
            @WebParam(name = "newPassword", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String newPassword)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/findUserRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/findUserResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/findUser/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "findUser", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.FindUser")
    @ResponseWrapper(localName = "findUserResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.FindUserResponse")
    @WebResult(name = "findUserReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public it.eng.hsm.test.itagile.firmaremota.ws.UserInfo findUser(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "userid", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String userid)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/verifySignaturesRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/verifySignaturesResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/verifySignatures/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "verifySignatures", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.VerifySignatures")
    @ResponseWrapper(localName = "verifySignaturesResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.VerifySignaturesResponse")
    @WebResult(name = "verifySignaturesReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public java.util.List<it.eng.hsm.test.itagile.firmaremota.ws.SignatureStatus> verifySignatures(
            @WebParam(name = "signedDocument", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] signedDocument,
            @WebParam(name = "docsInAttachment", targetNamespace = "http://ws.firmaremota.itagile.it") boolean docsInAttachment,
            @WebParam(name = "mimeType", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String mimeType)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/changePasswordRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/changePasswordResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/changePassword/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.ChangePasswordResponse")
    public void changePassword(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "newPassword", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String newPassword)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/signCAdESRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/signCAdESResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/signCAdES/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "signCAdES", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignCAdES")
    @ResponseWrapper(localName = "signCAdESResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignCAdESResponse")
    @WebResult(name = "signCAdESReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] signCAdES(
            @WebParam(name = "signatureCred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials signatureCred,
            @WebParam(name = "content", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] content,
            @WebParam(name = "digestType", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestType,
            @WebParam(name = "X509certificate", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] x509Certificate,
            @WebParam(name = "flags", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.SignatureFlags flags)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/documentXadesInfoRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/documentXadesInfoResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/documentXadesInfo/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "documentXadesInfo", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.DocumentXadesInfo")
    @ResponseWrapper(localName = "documentXadesInfoResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.DocumentXadesInfoResponse")
    @WebResult(name = "documentXadesInfoReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public it.eng.hsm.test.itagile.firmaremota.ws.SignatureDocumentInfo documentXadesInfo(
            @WebParam(name = "signedDocument", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] signedDocument,
            @WebParam(name = "verifySignatures", targetNamespace = "http://ws.firmaremota.itagile.it") boolean verifySignatures,
            @WebParam(name = "extractContent", targetNamespace = "http://ws.firmaremota.itagile.it") boolean extractContent,
            @WebParam(name = "extractX509", targetNamespace = "http://ws.firmaremota.itagile.it") boolean extractX509)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampResponseRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampResponseResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampResponse/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "timestampResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.TimestampResponse")
    @ResponseWrapper(localName = "timestampResponseResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.TimestampResponseResponse")
    @WebResult(name = "timestampResponseReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] timestampResponse(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "timeStampRequest", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] timeStampRequest)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/getUsersDirectoryTypeRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/getUsersDirectoryTypeResponse")
    @RequestWrapper(localName = "getUsersDirectoryType", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.GetUsersDirectoryType")
    @ResponseWrapper(localName = "getUsersDirectoryTypeResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.GetUsersDirectoryTypeResponse")
    @WebResult(name = "getUsersDirectoryTypeReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public java.lang.String getUsersDirectoryType();

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampAttachedRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampAttachedResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/timestampAttached/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "timestampAttached", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.TimestampAttached")
    @ResponseWrapper(localName = "timestampAttachedResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.TimestampAttachedResponse")
    @WebResult(name = "timestampAttachedReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] timestampAttached(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "content", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] content,
            @WebParam(name = "contentInAttachment", targetNamespace = "http://ws.firmaremota.itagile.it") boolean contentInAttachment,
            @WebParam(name = "digestAlg", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestAlg)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/getUserImagesRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/getUserImagesResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/getUserImages/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "getUserImages", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.GetUserImages")
    @ResponseWrapper(localName = "getUserImagesResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.GetUserImagesResponse")
    @WebResult(name = "getUserImagesReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public java.util.List<it.eng.hsm.test.itagile.firmaremota.ws.SignatureImage> getUserImages(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/signPKCS1Request", output = "http://ws.firmaremota.itagile.it/RemoteSignature/signPKCS1Response", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/signPKCS1/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "signPKCS1", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignPKCS1")
    @ResponseWrapper(localName = "signPKCS1Response", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignPKCS1Response")
    @WebResult(name = "signPKCS1Return", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] signPKCS1(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "digest", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] digest,
            @WebParam(name = "digestType", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestType,
            @WebParam(name = "X509certificate", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] x509Certificate)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/documentPdfInfoRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/documentPdfInfoResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/documentPdfInfo/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "documentPdfInfo", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.DocumentPdfInfo")
    @ResponseWrapper(localName = "documentPdfInfoResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.DocumentPdfInfoResponse")
    @WebResult(name = "documentPdfInfoReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public it.eng.hsm.test.itagile.firmaremota.ws.SignatureDocumentInfo documentPdfInfo(
            @WebParam(name = "signedDocument", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] signedDocument,
            @WebParam(name = "verifySignatures", targetNamespace = "http://ws.firmaremota.itagile.it") boolean verifySignatures,
            @WebParam(name = "extractFields", targetNamespace = "http://ws.firmaremota.itagile.it") boolean extractFields,
            @WebParam(name = "extractX509", targetNamespace = "http://ws.firmaremota.itagile.it") boolean extractX509)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/deleteUserRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/deleteUserResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/deleteUser/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.DeleteUserResponse")
    public void deleteUser(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "userid", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String userid)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/verifyCertificateAtTimeRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/verifyCertificateAtTimeResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/verifyCertificateAtTime/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "verifyCertificateAtTime", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.VerifyCertificateAtTime")
    @ResponseWrapper(localName = "verifyCertificateAtTimeResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.VerifyCertificateAtTimeResponse")
    @WebResult(name = "verifyCertificateAtTimeReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public it.eng.hsm.test.itagile.firmaremota.ws.CertificateStatus verifyCertificateAtTime(
            @WebParam(name = "certBuf", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] certBuf,
            @WebParam(name = "checkTime", targetNamespace = "http://ws.firmaremota.itagile.it") javax.xml.datatype.XMLGregorianCalendar checkTime)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/addUserRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/addUserResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/addUser/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "addUser", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.AddUserResponse")
    public void addUser(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "userid", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String userid,
            @WebParam(name = "password", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String password,
            @WebParam(name = "commonName", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String commonName,
            @WebParam(name = "email", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String email,
            @WebParam(name = "hsmManager", targetNamespace = "http://ws.firmaremota.itagile.it") boolean hsmManager,
            @WebParam(name = "userManager", targetNamespace = "http://ws.firmaremota.itagile.it") boolean userManager)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/openSignatureSessionRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/openSignatureSessionResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/openSignatureSession/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "openSignatureSession", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.OpenSignatureSession")
    @ResponseWrapper(localName = "openSignatureSessionResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.OpenSignatureSessionResponse")
    @WebResult(name = "openSignatureSessionReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public java.lang.String openSignatureSession(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred)
            throws RemoteSignatureExceptionException;

    @WebMethod(operationName = "documentP7mInfo")
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/documentP7mInfoRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/documentP7mInfoResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/documentP7mInfo/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "documentP7mInfo", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.DocumentP7MInfo")
    @ResponseWrapper(localName = "documentP7mInfoResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.DocumentP7MInfoResponse")
    @WebResult(name = "documentP7mInfoReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public it.eng.hsm.test.itagile.firmaremota.ws.SignatureDocumentInfo documentP7MInfo(
            @WebParam(name = "signedDocument", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] signedDocument,
            @WebParam(name = "verifySignatures", targetNamespace = "http://ws.firmaremota.itagile.it") boolean verifySignatures,
            @WebParam(name = "extractContent", targetNamespace = "http://ws.firmaremota.itagile.it") boolean extractContent,
            @WebParam(name = "extractOriginal", targetNamespace = "http://ws.firmaremota.itagile.it") boolean extractOriginal,
            @WebParam(name = "extractX509", targetNamespace = "http://ws.firmaremota.itagile.it") boolean extractX509)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/signPDFRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/signPDFResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/signPDF/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "signPDF", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignPDF")
    @ResponseWrapper(localName = "signPDFResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignPDFResponse")
    @WebResult(name = "signPDFReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] signPDF(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "content", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] content,
            @WebParam(name = "contentInAttachments", targetNamespace = "http://ws.firmaremota.itagile.it") boolean contentInAttachments,
            @WebParam(name = "digestType", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestType,
            @WebParam(name = "X509certificate", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] x509Certificate,
            @WebParam(name = "flags", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.SignatureFlags flags,
            @WebParam(name = "fieldName", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String fieldName,
            @WebParam(name = "page", targetNamespace = "http://ws.firmaremota.itagile.it") int page,
            @WebParam(name = "x", targetNamespace = "http://ws.firmaremota.itagile.it") int x,
            @WebParam(name = "y", targetNamespace = "http://ws.firmaremota.itagile.it") int y,
            @WebParam(name = "width", targetNamespace = "http://ws.firmaremota.itagile.it") int width,
            @WebParam(name = "height", targetNamespace = "http://ws.firmaremota.itagile.it") int height,
            @WebParam(name = "userName", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String userName,
            @WebParam(name = "reason", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String reason,
            @WebParam(name = "location", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String location,
            @WebParam(name = "dateFormat", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String dateFormat,
            @WebParam(name = "text", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String text,
            @WebParam(name = "fontSize", targetNamespace = "http://ws.firmaremota.itagile.it") int fontSize)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/signPKCS1ArrayRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/signPKCS1ArrayResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/signPKCS1Array/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "signPKCS1Array", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignPKCS1Array")
    @ResponseWrapper(localName = "signPKCS1ArrayResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignPKCS1ArrayResponse")
    @WebResult(name = "signPKCS1ArrayReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public java.util.List<byte[]> signPKCS1Array(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "digest", targetNamespace = "http://ws.firmaremota.itagile.it") java.util.List<byte[]> digest,
            @WebParam(name = "digestType", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestType,
            @WebParam(name = "X509certificate", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] x509Certificate)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/getCertificatesRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/getCertificatesResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/getCertificates/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "getCertificates", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.GetCertificates")
    @ResponseWrapper(localName = "getCertificatesResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.GetCertificatesResponse")
    @WebResult(name = "getCertificatesReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public java.util.List<byte[]> getCertificates(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/setUserImageRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/setUserImageResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/setUserImage/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "setUserImage", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SetUserImage")
    @ResponseWrapper(localName = "setUserImageResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SetUserImageResponse")
    public void setUserImage(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "userImage", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.SignatureImage userImage)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/signXAdESRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/signXAdESResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/signXAdES/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "signXAdES", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignXAdES")
    @ResponseWrapper(localName = "signXAdESResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignXAdESResponse")
    @WebResult(name = "signXAdESReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] signXAdES(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "content", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] content,
            @WebParam(name = "digestType", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestType,
            @WebParam(name = "certificate", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] certificate,
            @WebParam(name = "params", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureXadesParams params)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/isModuleActiveRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/isModuleActiveResponse")
    @RequestWrapper(localName = "isModuleActive", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.IsModuleActive")
    @ResponseWrapper(localName = "isModuleActiveResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.IsModuleActiveResponse")
    @WebResult(name = "isModuleActiveReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public boolean isModuleActive(
            @WebParam(name = "moduleName", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String moduleName);

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/closeSignatureSessionRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/closeSignatureSessionResponse")
    @RequestWrapper(localName = "closeSignatureSession", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.CloseSignatureSession")
    @ResponseWrapper(localName = "closeSignatureSessionResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.CloseSignatureSessionResponse")
    @WebResult(name = "closeSignatureSessionReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public java.lang.String closeSignatureSession(
            @WebParam(name = "cred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials cred,
            @WebParam(name = "sessionToken", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String sessionToken);

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/signP7MRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/signP7MResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/signP7M/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "signP7M", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignP7M")
    @ResponseWrapper(localName = "signP7MResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignP7MResponse")
    @WebResult(name = "signP7MReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] signP7M(
            @WebParam(name = "signatureCred", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureCredentials signatureCred,
            @WebParam(name = "content", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] content,
            @WebParam(name = "contentInAttachments", targetNamespace = "http://ws.firmaremota.itagile.it") boolean contentInAttachments,
            @WebParam(name = "p7m", targetNamespace = "http://ws.firmaremota.itagile.it") boolean p7M,
            @WebParam(name = "digestType", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestType,
            @WebParam(name = "X509certificate", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] x509Certificate,
            @WebParam(name = "flags", targetNamespace = "http://ws.firmaremota.itagile.it") it.eng.hsm.test.itagile.firmaremota.ws.SignatureFlags flags)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/digestRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/digestResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/digest/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "digest", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.Digest")
    @ResponseWrapper(localName = "digestResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.DigestResponse")
    @WebResult(name = "digestReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public byte[] digest(
            @WebParam(name = "content", targetNamespace = "http://ws.firmaremota.itagile.it") byte[] content,
            @WebParam(name = "digestAlg", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String digestAlg)
            throws RemoteSignatureExceptionException;

    @WebMethod
    @Action(input = "http://ws.firmaremota.itagile.it/RemoteSignature/signPDFPathRequest", output = "http://ws.firmaremota.itagile.it/RemoteSignature/signPDFPathResponse", fault = {
            @FaultAction(className = RemoteSignatureExceptionException.class, value = "http://ws.firmaremota.itagile.it/RemoteSignature/signPDFPath/Fault/RemoteSignatureException_Exception") })
    @RequestWrapper(localName = "signPDFPath", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignPDFPath")
    @ResponseWrapper(localName = "signPDFPathResponse", targetNamespace = "http://ws.firmaremota.itagile.it", className = "it.eng.hsm.test.itagile.firmaremota.ws.SignPDFPathResponse")
    @WebResult(name = "signPDFPathReturn", targetNamespace = "http://ws.firmaremota.itagile.it")
    public int signPDFPath(
            @WebParam(name = "userid", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String userid,
            @WebParam(name = "password", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String password,
            @WebParam(name = "pinToSign", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String pinToSign,
            @WebParam(name = "domain", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String domain,
            @WebParam(name = "dirSource", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String dirSource,
            @WebParam(name = "dirDest", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String dirDest,
            @WebParam(name = "fieldName", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String fieldName,
            @WebParam(name = "page", targetNamespace = "http://ws.firmaremota.itagile.it") int page,
            @WebParam(name = "x", targetNamespace = "http://ws.firmaremota.itagile.it") int x,
            @WebParam(name = "y", targetNamespace = "http://ws.firmaremota.itagile.it") int y,
            @WebParam(name = "width", targetNamespace = "http://ws.firmaremota.itagile.it") int width,
            @WebParam(name = "height", targetNamespace = "http://ws.firmaremota.itagile.it") int height,
            @WebParam(name = "userName", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String userName,
            @WebParam(name = "reason", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String reason,
            @WebParam(name = "location", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String location,
            @WebParam(name = "dateFormat", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String dateFormat,
            @WebParam(name = "graphic", targetNamespace = "http://ws.firmaremota.itagile.it") boolean graphic,
            @WebParam(name = "text", targetNamespace = "http://ws.firmaremota.itagile.it") java.lang.String text,
            @WebParam(name = "fontSize", targetNamespace = "http://ws.firmaremota.itagile.it") int fontSize)
            throws RemoteSignatureExceptionException;
}
