package it.eng.hsm.test.itagile.firmaremota.ws;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1 2017-08-29T17:56:04.066+02:00 Generated source version:
 * 2.7.14.redhat-1
 */

@WebFault(name = "fault", targetNamespace = "http://ws.firmaremota.itagile.it")
public class RemoteSignatureExceptionException extends Exception {

    private it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureException fault;

    public RemoteSignatureExceptionException() {
        super();
    }

    public RemoteSignatureExceptionException(String message) {
        super(message);
    }

    public RemoteSignatureExceptionException(String message, Throwable cause) {
        super(message, cause);
    }

    public RemoteSignatureExceptionException(String message,
            it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureException fault) {
        super(message);
        this.fault = fault;
    }

    public RemoteSignatureExceptionException(String message,
            it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public it.eng.hsm.test.itagile.firmaremota.ws.RemoteSignatureException getFaultInfo() {
        return this.fault;
    }
}